<?php

require_once dirname(__FILE__) . '/../../../../../GithubBrag/GithubBragWidget.php';

/**
 * Test class for GithubBragWidget.
 * Generated by PHPUnit on 2013-03-12 at 23:01:51.
 */
class GithubBragWidgetTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var GithubBragWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GithubBragWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testWidget().
     */
    public function testWidget()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
