<?php

namespace GithubBrag;

require_once dirname(__FILE__) . '/../../../../../GithubBrag/TestClass.php';

/**
 * Test class for TestClass.
 * Generated by PHPUnit on 2013-03-12 at 23:01:51.
 */
class TestClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TestClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}

?>
